import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class Day11Test {
    @Test
    fun testSolve1() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        val solution = Day11().solve1(input)
        assertEquals(374, solution)
    }

    @Test
    fun testSolve2a() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        val solution = Day11().solve2(input, 2)
        assertEquals(374, solution)
    }

    @Test
    fun testSolve2b() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        val solution = Day11().solve2(input, 10)
        assertEquals(1030, solution)
    }

    @Test
    fun testSolve2c() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        val solution = Day11().solve2(input, 100)
        assertEquals(8410, solution)
    }
}